@server = http://localhost:4004

### Customers
# @name Customers_GET
GET {{server}}/odata/v4/services/Customers


### Customers
# @name Customers_POST
POST {{server}}/odata/v4/services/Customers
Content-Type: application/json

{
  "ID": "14205978-8ce5-4684-91a1-3d3644c07b05",
  "Name": "Name-14205978",
  "Email": "Email-14205978",
  "Phone": "Phone-14205978",
  "Address": "Address-14205978",
  "Cep": "14205978",
  "City": "City-14205978",
  "Country": "Country-14205978",
  "CreatedAt": "2016-10-18T00:00:00.000Z",
  "UpdatedAt": "2019-02-26T00:00:00.000Z"
}


### Customers
# @name Customers_PATCH
PATCH {{server}}/odata/v4/services/Customers/14205978-8ce5-4684-91a1-3d3644c07b05
Content-Type: application/json

{
  "ID": "14205978-8ce5-4684-91a1-3d3644c07b05",
  "Name": "Name-14205978",
  "Email": "Email-14205978",
  "Phone": "Phone-14205978",
  "Address": "Address-14205978",
  "Cep": "14205978",
  "City": "City-14205978",
  "Country": "Country-14205978",
  "CreatedAt": "2016-10-18T00:00:00.000Z",
  "UpdatedAt": "2019-02-26T00:00:00.000Z"
}


### Customers
# @name Customers_DELETE
DELETE {{server}}/odata/v4/services/Customers/
Content-Type: application/json


